mariadb:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
  container_name: mariadb
  ports:
    - 3307:3306
  volumes:
     - /home/grman/docker/volumes/mariadb/data:/var/lib/mysql
     - /home/grman/docker/volumes/mariadb/cp:/home/grman/docker/volumes/postmariadbgres/cp
