mariadb:
  image: mariadb:latest
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
  container_name: mariadb
  ports:
    - 3307:3306
  volumes:
     - ./data:/data
