postgres:
  image: postgres:latest
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  container_name: postgres
  ports:
    - 5431:5432
  volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./data:/data
